# Generated by Django 5.1.6 on 2025-02-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.IntegerField(max_length=10)),
                ('curso', models.CharField(choices=[('informatica', 'Informatica Para Internet'), ('quimica', 'Quimica'), ('agropecuaria', 'Agropecuaria')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
