# Generated by Django 5.1.6 on 2025-02-17 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now=True)),
                ('date_devolucao', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alunos')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.livros')),
            ],
        ),
    ]
