# Generated by Django 5.1.6 on 2025-02-17 21:16

import core.models.emprestimo
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alunos_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alunos', validators=[core.models.emprestimo.validate_studant]),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.livros', validators=[core.models.emprestimo.validate_book]),
        ),
    ]
